#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace Kyoshin_Chassis_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Akm { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_WeaponCollision { struct FAnimBlueprintGeneratedConstantData; }

namespace STR_Rank { struct FSTR_Rank; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace ABP_GripPoses { struct FAnimBlueprintGeneratedConstantData; }

namespace Bodycam { struct FSTR_Rank; }

namespace ABP_Procedural_Sway { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PostOverlay { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Procedural_GoPro { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_W_DroneController { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Procedural_IK { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Overlay_Default { struct FAnimBlueprintGeneratedConstantData; }

namespace Viewmodel { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Goggles { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_HorrorMob { struct FAnimBlueprintGeneratedConstantData; }


namespace ABP_Overlay_Tablet
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Lobby_Anim
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Procedural_Additives
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Procedural_AimOffset
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ALS_AnimBP_0
{
	class UALS_AnimBP_C;
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Procedural_Viewmodel
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace abp_Raven_01_03_spline
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Tablet
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Procedural_ApplyViewmodel
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ALS_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	class UALS_AnimBP_C;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace AnimBP_Zombie
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Overlay_Rifle
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
